executable = /afs/desy.de/user/b/bliewert/public/MarlinWorkdirs/MEM_HEP/jobs/2023-06-08_a/job_zhh.sh
arguments = $(file) $(ProcId)
should_transfer_files = True
transfer_executable = True

Requirements = (OpSysAndVer == "CentOS7")
request_cpus = 1
request_memory = 2000 Mb

log = /nfs/dust/ilc/user/bliewert/fullflow_v3/zhh/log/$(ProcId).log
output = /nfs/dust/ilc/user/bliewert/fullflow_v3/zhh/log/$(ProcId).out
error = /nfs/dust/ilc/user/bliewert/fullflow_v3/zhh/log/$(ProcId).err

queue file from /afs/desy.de/user/b/bliewert/public/MarlinWorkdirs/MEM_HEP/jobs/2023-06-08_a/queue_zhh.txt
